'use client'
import './globals.css'
import { CrossmarkAdaptor, WalletConnectAdaptor, XummAdaptor } from '@xrpl-wallet/adaptors'
// import type { Metadata } from 'next'
import { WalletAdaptor } from '@xrpl-wallet/core'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'

import Provider from './Provider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const walletmetadata = [
  { adaptor: 'xumm', props: { apiKey: '7fcb00b9-b846-4ddf-ae02-2a94f18c0b2f' } },
  { adaptor: 'crossmark' },
  { adaptor: 'walletconnect', props: { title: 'WalletConnect' } },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [adaptors, setAdaptors] = useState<WalletAdaptor[]>([])

  useEffect(() => {
    const xumm = new XummAdaptor({ apiKey: '7fcb00b9-b846-4ddf-ae02-2a94f18c0b2f' })
    const crossmark = new CrossmarkAdaptor()
    const walletconnect = new WalletConnectAdaptor({
      projectId: '85ad846d8aa771cd56c2bbbf30f7a183',
      network: 'testnet',
    })
    setAdaptors([xumm, crossmark, walletconnect])
  }, [])

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider adaptors={adaptors} metadata={walletmetadata}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
